[config]

[templates.waybar]
input_path = "/home/eon/.config/matugen/templates/waybar-colors.template"
output_path = "/home/eon/.config/waybar/colors.css"
post_hook = "pkill waybar; setsid waybar > /tmp/waybar.log 2>&1 & disown"

[templates.mango]
input_path = "/home/eon/.config/matugen/templates/mango-colors.template"
output_path = "/home/eon/.config/mango/colors.conf"
post_hook = "mmsg dispatch reload_config"

[templates.kitty]
input_path = "/home/eon/.config/matugen/templates/kitty-colors.template"
output_path = "/home/eon/.config/kitty/colors.conf"

[templates.gtk4]
input_path = "/home/eon/.config/matugen/templates/gtk-colors.template"
output_path = "/home/eon/.config/gtk-4.0/gtk.css"

[templates.mako]
input_path = "/home/eon/.config/matugen/templates/mako-colors.template"
output_path = "/home/eon/.config/mako/colors"
post_hook = "makoctl reload"
